// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("rescript/lib/js/caml_array.js");

var myArr = [
  1,
  2,
  3
];

Caml_array.set(myArr, 1, 2);

console.log(myArr);

var pushedVal = myArr.push(22);

console.log(myArr.length);

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 2,
      tl: /* [] */0
    }
  }
};

exports.myArr = myArr;
exports.pushedVal = pushedVal;
exports.myList = myList;
/*  Not a pure module */
