// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Demo9PartTwo = require("./Demo9PartTwo.bs.js");

function add(a, b) {
  return a + b | 0;
}

var MyMath = {
  add: add
};

function add$1(a, b) {
  return a + b | 0;
}

function minus(a, b) {
  return a - b | 0;
}

var MyMath1 = {
  add: add$1,
  minus: minus
};

Demo9PartTwo.minus(33, 3);

exports.MyMath = MyMath;
exports.MyMath1 = MyMath1;
/*  Not a pure module */
