// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var y = {
  contents: 5
};

y.contents = 10;

y.contents = 6;

console.log(y);

console.log(y.contents);

var x = 5;

exports.x = x;
exports.y = y;
/*  Not a pure module */
