// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function handleAnswer1(a) {
  if (a === /* Yes */0) {
    return "foo";
  } else {
    return "boo";
  }
}

function handleAnswer3(a) {
  if (a === /* Yes */0) {
    return "foo";
  } else if (a === /* No */1) {
    return "boo";
  } else {
    return "yoo";
  }
}

function handleAnswer5(a) {
  if (a === /* Yes */0) {
    return "foo";
  } else if (a === /* No */1) {
    return "boo";
  } else if (a === /* Maybe */2) {
    return "yoo";
  } else {
    return "koo";
  }
}

function handleAnswer6(a) {
  switch (a) {
    case /* Yes */0 :
        return "gg";
    case /* No */1 :
        return "mg";
    case /* Maybe */2 :
        return "other cases";
    
  }
}

function handleAnswer7(a) {
  if (typeof a === "number") {
    return "other cases";
  }
  switch (a.TAG | 0) {
    case /* Yes */0 :
        return "gg" + String(a._0);
    case /* No */1 :
        return a._0;
    case /* Confused */2 :
        return String(a._0);
    
  }
}

String(8);

var x = String(8);

console.log(x);

exports.handleAnswer1 = handleAnswer1;
exports.handleAnswer3 = handleAnswer3;
exports.handleAnswer5 = handleAnswer5;
exports.handleAnswer6 = handleAnswer6;
exports.handleAnswer7 = handleAnswer7;
exports.x = x;
/*  Not a pure module */
