// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Demo2 = require("./Demo2.bs.js");

var answer = Demo2.divideBy2(6);

console.log("John");

function make(count) {
  if (count !== 1) {
    if (count !== 2) {
      String(count) + " times";
    } else {
      
    }
  }
  
}

var Button = {
  make: make
};

var person = [
  "John",
  50,
  6
];

var name = "John";

var age = 50;

var ht = 6;

exports.answer = answer;
exports.person = person;
exports.name = name;
exports.age = age;
exports.ht = ht;
exports.Button = Button;
/* answer Not a pure module */
