// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function addOne(n) {
  if (n !== undefined) {
    return n + 1 | 0;
  } else {
    return 0;
  }
}

function addOne1(n) {
  if (n !== undefined) {
    return n + 1 | 0;
  } else {
    return 0;
  }
}

var ans = 1 + 1 | 0;

console.log(ans);

function validateAge(a) {
  if (a > 150) {
    return {
            TAG: /* Error */0,
            _0: "Invalid age"
          };
  } else {
    return {
            TAG: /* Ok */1,
            _0: a
          };
  }
}

var result = {
  TAG: /* Error */0,
  _0: "Invalid age"
};

console.log(result);

var result1;

result1 = result.TAG === /* Error */0 ? "Invalid age" : String("Invalid age");

console.log(result1);

exports.addOne = addOne;
exports.addOne1 = addOne1;
exports.ans = ans;
exports.validateAge = validateAge;
exports.result = result;
exports.result1 = result1;
/*  Not a pure module */
