// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function divideBy2(x) {
  return x / 2 | 0;
}

console.log(1);

function divideBy2Float(x) {
  return x / 2;
}

function add(a, b) {
  return a + b | 0;
}

function concatString(a, b) {
  return a + b;
}

function divideBy2Float$1(x) {
  return x / 2;
}

var Maths = {
  divideBy2Float: divideBy2Float$1
};

var x = "abc";

var y = "ab";

var z = /* 'a' */97;

var myNumber = 5;

var myFloat = 10.9;

var ans = 1;

exports.x = x;
exports.y = y;
exports.z = z;
exports.myNumber = myNumber;
exports.myFloat = myFloat;
exports.divideBy2 = divideBy2;
exports.ans = ans;
exports.divideBy2Float = divideBy2Float;
exports.add = add;
exports.concatString = concatString;
exports.Maths = Maths;
/*  Not a pure module */
