// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("rescript/lib/js/caml_int32.js");

function sum(a, b) {
  return a + b | 0;
}

function add5(param) {
  return 5 + param | 0;
}

function add10(param) {
  return 10 + param | 0;
}

function $$double(n) {
  return (n << 1);
}

var ans1 = 9;

console.log(ans1);

var ans = 36;

console.log(ans);

var ans2 = 36;

function subtract(a, b) {
  return a - b | 0;
}

console.log(3);

var divide = Caml_int32.div;

console.log(3);

var ans3 = 3;

var ans4 = 3;

exports.sum = sum;
exports.add5 = add5;
exports.add10 = add10;
exports.$$double = $$double;
exports.ans1 = ans1;
exports.ans = ans;
exports.ans2 = ans2;
exports.subtract = subtract;
exports.ans3 = ans3;
exports.divide = divide;
exports.ans4 = ans4;
/*  Not a pure module */
