// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

var person = {
  name: "Jake",
  age: 67
};

console.log(person.name);

person.name = "Joe";

var person1 = {
  name: "Jake",
  age: 67
};

console.log(person1.name);

var myPoint = {
  x: 1.0,
  y: 2.0,
  z: 3.0
};

Curry._2(document.addEventListener, "mouseup", (function (_event) {
        console.log("clicked!");
        
      }));

var loc = document.location;

document.location.href = "rescript-lang.org";

exports.person = person;
exports.person1 = person1;
exports.myPoint = myPoint;
exports.loc = loc;
/*  Not a pure module */
