// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");

console.log("hello", "hi", "heyo", "hola", "hi there");

[
    1,
    2,
    3
  ].concat([
      2,
      3,
      2
    ]);

var ans = [
    1,
    2,
    3
  ].concat([
      2,
      3,
      2
    ]);

console.log(ans);

function getNonZero(n) {
  if (n === 0) {
    return ;
  } else {
    return n;
  }
}

console.log(undefined);

var ans1 = 10;

console.log(ans1);

Belt_Option.getExn(4);

var ans2 = Belt_Option.getExn(4);

console.log(ans2);

var ans3 = Belt_Option.getWithDefault(undefined, 19);

console.log(ans3);

var ans$1;

exports.getNonZero = getNonZero;
exports.ans = ans$1;
exports.ans1 = ans1;
exports.ans2 = ans2;
exports.ans3 = ans3;
/*  Not a pure module */
